//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_HoaDon()
        {
            this.Tb_Ve = new HashSet<Tb_Ve>();
        }
    
        public long Ma_HoaDon { get; set; }
        public string UserName { get; set; }
        public Nullable<long> Ma_LichChieu_PhongChieu { get; set; }
        public Nullable<long> GiaTien { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<long> ThanhTien { get; set; }
        public Nullable<long> Ma_TT { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual Tb_LichChieu_PhongChieu Tb_LichChieu_PhongChieu { get; set; }
        public virtual Tb_NguoiDung Tb_NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ve> Tb_Ve { get; set; }
        public virtual Tb_ThanhToan Tb_ThanhToan { get; set; }
    }
}
