//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_LichChieu_PhongChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_LichChieu_PhongChieu()
        {
            this.Tb_HoaDon = new HashSet<Tb_HoaDon>();
            this.Tb_Ve = new HashSet<Tb_Ve>();
        }
    
        public long Ma_LichChieu_PhongChieu { get; set; }
        public Nullable<long> Ma_Phim { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public Nullable<System.TimeSpan> GioChieu { get; set; }
        public string Ma_PhongChieu { get; set; }
        public Nullable<bool> available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_HoaDon> Tb_HoaDon { get; set; }
        public virtual Tb_phim Tb_phim { get; set; }
        public virtual Tb_Phong Tb_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ve> Tb_Ve { get; set; }
    }
}
