//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_NguoiDung()
        {
            this.Tb_HoaDon = new HashSet<Tb_HoaDon>();
        }
        [Required(ErrorMessage = "Nhập tài khoản")]
        public string UserName { get; set; }
        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,60}$", ErrorMessage = "Mật khẩu phải chứa ít nhất 1 chữ cái thường, 1 chữ cái hoa, 1 số và có độ dài từ 8 ký tự trở lên")]
        public string PassWord { get; set; }
        [Required(ErrorMessage = "Nhập tên người dùng")]
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "email không hợp lệ")]
        public string Email { get; set; }
        public Nullable<bool> available { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_HoaDon> Tb_HoaDon { get; set; }
    }
}
