//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_phim()
        {
            this.Tb_LichChieu_PhongChieu = new HashSet<Tb_LichChieu_PhongChieu>();
        }
    
        public long Ma_Phim { get; set; }
        public string TenPhim { get; set; }
        public string ChatLuong { get; set; }
        public string Ma_Loai { get; set; }
        public string Ma_TheLoai { get; set; }
        public string DaoDien { get; set; }
        public string DienVien { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public string NgonNgu { get; set; }
        public string NoiDung { get; set; }
        public string AnhBia { get; set; }
        public string Trailer { get; set; }
        public Nullable<bool> available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_LichChieu_PhongChieu> Tb_LichChieu_PhongChieu { get; set; }
        public virtual Tb_PhanLoaiPhim Tb_PhanLoaiPhim { get; set; }
        public virtual Tb_TheLoai Tb_TheLoai { get; set; }
    }
}
