//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PhongGhe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_PhongGhe()
        {
            this.Tb_Ve = new HashSet<Tb_Ve>();
        }
    
        public long Ma_PhongGhe { get; set; }
        public string Ma_PhongChieu { get; set; }
        public string TenGhe { get; set; }
        public string Ma_LoaiGhe { get; set; }
    
        public virtual Tb_LoaiGhe Tb_LoaiGhe { get; set; }
        public virtual Tb_Phong Tb_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ve> Tb_Ve { get; set; }
    }
}
