//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Phong()
        {
            this.Tb_LichChieu_PhongChieu = new HashSet<Tb_LichChieu_PhongChieu>();
            this.Tb_PhongGhe = new HashSet<Tb_PhongGhe>();
        }
    
        public string Ma_PhongChieu { get; set; }
        public string LoaiPhong { get; set; }
        public Nullable<int> SoLuongGhe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_LichChieu_PhongChieu> Tb_LichChieu_PhongChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_PhongGhe> Tb_PhongGhe { get; set; }
    }
}
