//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Ve
    {
        public long Ma_ve { get; set; }
        public Nullable<long> Ma_HoaDon { get; set; }
        public Nullable<long> Ma_LichChieu_PhongChieu { get; set; }
        public Nullable<long> Ma_PhongGhe { get; set; }
    
        public virtual Tb_HoaDon Tb_HoaDon { get; set; }
        public virtual Tb_LichChieu_PhongChieu Tb_LichChieu_PhongChieu { get; set; }
        public virtual Tb_PhongGhe Tb_PhongGhe { get; set; }
    }
}
